# Imports

In [1]:
import numpy as np
%load_ext autoreload
%autoreload 2

In [2]:
import os
import warnings
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import torch
from torchtnt.utils.flops import FlopTensorDispatchMode
from tqdm import tqdm

from utils import num_params
from utils.postprocess import load_result_dataframe, last_epoch_only

W0719 12:21:53.926000 69886 site-packages/torch/distributed/elastic/multiprocessing/redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.

In [3]:
sns.set(font_scale=1.25, style="whitegrid")

# Ignore known warnings that come when constructing subnets.
warnings.filterwarnings("ignore", message=".*The parameter 'pretrained' is deprecated.*")
warnings.filterwarnings("ignore", message=".*Arguments other than a weight enum.*")
warnings.filterwarnings("ignore", message=".*already erased node.*")

# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
# print(f"Using device = {device}")

NUM_CORES = os.cpu_count()
if hasattr(os, "sched_getaffinity"):
    # This function is only available on certain platforms. When running with Slurm, it can tell us the true
    # number of cores we have access to.
    NUM_CORES = len(os.sched_getaffinity(0))
print (f"Using {NUM_CORES} cores.")

Using 8 cores.

# Scan Files

Find and load all result files.

In [4]:
project_name = "moe/conv4/multitask"
proj_dir = Path("../experiments") / project_name

In [5]:
full_df = load_result_dataframe(proj_dir, calc_sizes=False, meta_required=False, include_location=True)

100%|██████████| 519/519 [00:00<00:00, 4126.91it/s]

In [6]:
full_df

                                                                      Step  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0         0
                                                          1563 1      1563
                                                          3126 2      3126
                                                          4689 3      4689
                                                          6252 4      6252
...                                                                    ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6      1176
                                                          1372 7      1372
                                                          1568 8      1568
                                                          1764 9      1764
                                                          1960 10     1960

                                                                      Time/Data  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0            NaN
                                                          1563 1       0.000493
                                                          3126 2       0.000365
                                                          4689 3       0.000616
                                                          6252 4       0.016904
...                                                                         ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6       0.000154
                                                          1372 7       0.000142
                                                          1568 8       0.000237
                                                          1764 9       0.000149
                                                          1960 10      0.000120

                                                                            LR  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0           NaN
                                                          1563 1      0.010000
                                                          3126 2      0.009755
                                                          4689 3      0.009045
                                                          6252 4      0.007939
...                                                                        ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6      0.000500
                                                          1372 7      0.000345
                                                          1568 8      0.000206
                                                          1764 9      0.000095
                                                          1960 10     0.000024

                                                                          Loss  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0           NaN
                                                          1563 1      8.298564
                                                          3126 2      7.798619
                                                          4689 3      6.146111
                                                          6252 4      7.751478
...                                                                        ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6      2.257630
                                                          1372 7      2.080603
                                                          1568 8      2.138665
                                                          1764 9      2.251265
                                                          1960 10     2.172788

                                                                      Time/Img Per Sec  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                   NaN
                                                          1563 1           1448.809672
                                                          3126 2           6749.086228
                                                          4689 3           6523.784267
                                                          6252 4           3983.383826
...                                                                                ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6           7992.503340
                                                          1372 7           7928.919455
                                                          1568 8           7968.281168
                                                          1764 9           8003.715060
                                                          1960 10          7899.054682

                                                                          GPU Mem  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0              NaN
                                                          1563 1       869.673340
                                                          3126 2       869.673340
                                                          4689 3       869.673340
                                                          6252 4       869.673340
...                                                                           ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6      6489.509766
                                                          1372 7      6489.509766
                                                          1568 8      6489.509766
                                                          1764 9      6489.509766
                                                          1960 10     6489.509766

                                                                          Proc Mem  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0               NaN
                                                          1563 1       3347.792969
                                                          3126 2       3501.371094
                                                          4689 3       3873.554688
                                                          6252 4       3878.246094
...                                                                            ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6      13159.953125
                                                          1372 7      13158.453125
                                                          1568 8      13161.261719
                                                          1764 9      13164.542969
                                                          1960 10     13163.015625

                                                                      cifar100/Main Loss  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                     NaN
                                                          1563 1               11.991222
                                                          3126 2               14.016890
                                                          4689 3                9.869000
                                                          6252 4               12.306745
...                                                                                  ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                3.231484
                                                          1372 7                2.925105
                                                          1568 8                3.132481
                                                          1764 9                3.368528
                                                          1960 10               3.117944

                                                                      fer2013/Main Loss  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                    NaN
                                                          1563 1               2.990886
                                                          3126 2               1.897375
                                                          4689 3               2.556194
                                                          6252 4               2.921290
...                                                                                 ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                    NaN
                                                          1372 7                    NaN
                                                          1568 8                    NaN
                                                          1764 9                    NaN
                                                          1960 10                   NaN

                                                                      resisc45/Main Loss  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                     NaN
                                                          1563 1                9.913584
                                                          3126 2                7.481592
                                                          4689 3                6.013138
                                                          6252 4                8.026400
...                                                                                  ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                1.283776
                                                          1372 7                1.236100
                                                          1568 8                1.144848
                                                          1764 9                1.134002
                                                          1960 10               1.227632

                                                                      ...  \
location                                           seed   Step Epoch  ...
3-tasks/probing/cifar-stage-1-4                    111213 0    0      ...
                                                          1563 1      ...
                                                          3126 2      ...
                                                          4689 3      ...
                                                          6252 4      ...
...                                                                   ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6      ...
                                                          1372 7      ...
                                                          1568 8      ...
                                                          1764 9      ...
                                                          1960 10     ...

                                                                      Overall/Train fmow/Main Loss  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                               NaN
                                                          1563 1                               NaN
                                                          3126 2                               NaN
                                                          4689 3                               NaN
                                                          6252 4                               NaN
...                                                                                            ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                               NaN
                                                          1372 7                               NaN
                                                          1568 8                               NaN
                                                          1764 9                               NaN
                                                          1960 10                              NaN

                                                                      Overall/Train sun397/Main Loss  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                                 NaN
                                                          1563 1                                 NaN
                                                          3126 2                                 NaN
                                                          4689 3                                 NaN
                                                          6252 4                                 NaN
...                                                                                              ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                                 NaN
                                                          1372 7                                 NaN
                                                          1568 8                                 NaN
                                                          1764 9                                 NaN
                                                          1960 10                                NaN

                                                                      Overall/Train dtd/Accuracy  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                             NaN
                                                          1563 1                             NaN
                                                          3126 2                             NaN
                                                          4689 3                             NaN
                                                          6252 4                             NaN
...                                                                                          ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                             NaN
                                                          1372 7                             NaN
                                                          1568 8                             NaN
                                                          1764 9                             NaN
                                                          1960 10                            NaN

                                                                      Overall/Train flowers/Accuracy  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                                 NaN
                                                          1563 1                                 NaN
                                                          3126 2                                 NaN
                                                          4689 3                                 NaN
                                                          6252 4                                 NaN
...                                                                                              ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                                 NaN
                                                          1372 7                                 NaN
                                                          1568 8                                 NaN
                                                          1764 9                                 NaN
                                                          1960 10                                NaN

                                                                      Overall/Train fmow/Accuracy  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                              NaN
                                                          1563 1                              NaN
                                                          3126 2                              NaN
                                                          4689 3                              NaN
                                                          6252 4                              NaN
...                                                                                           ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                              NaN
                                                          1372 7                              NaN
                                                          1568 8                              NaN
                                                          1764 9                              NaN
                                                          1960 10                             NaN

                                                                      Overall/Train sun397/Accuracy  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                                NaN
                                                          1563 1                                NaN
                                                          3126 2                                NaN
                                                          4689 3                                NaN
                                                          6252 4                                NaN
...                                                                                             ...
cifar-resisc-only/stitch-into-resisc/rand+resis... 67890  1176 6                                NaN
                                                          1372 7                                NaN
                                                          1568 8                                NaN
                                                          1764 9                                NaN
                                                          1960 10                               NaN

                                                                      Overall/dtd/Test Accuracy  \
location                                           seed   Step Epoch
3-tasks/probing/cifar-stage-1-4                    111213 0    0                            NaN
                                                          1563 1                            NaN
                                                          3126 2                            NaN
                                                          4689 3                            NaN
                                                          6252 4                            NaN

Filter down to just the final performance: i.e., the last epoch number. After that, parse folder names to get additional meta columns.

In [7]:
def get_model_type(loc):
    """ Turns 'stitch-into-(cifar|resisc)' to 'cifar' or 'resisc'. """
    base = Path(loc).parts[1]
    return base if base == "probing" else base.split("-")[-1]

final_df = last_epoch_only(full_df)
final_df.reset_index("location", inplace=True)
# Option below to filter out extraneous runs in subfolders. Otherwise each becomes a different Stitch Method.
# final_df = final_df.loc[final_df["location"].str.count("/") < 3].copy()
final_df["Task Type"] = final_df["location"].apply(lambda loc: Path(loc).parts[0])
final_df["Model Type"] = final_df["location"].apply(get_model_type)
final_df["Stitch Method"] = final_df["location"].apply(lambda loc: str(Path(*Path(loc).parts[2:])))
final_df.drop(columns=["location", "Step"], inplace=True)
final_df.set_index(["Task Type", "Model Type", "Stitch Method"], append=True, inplace=True)
final_df

                                                                        Time/Data  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4          0.015466
12345  15630 10    3-tasks           probing    cifar-stage-1-4          0.000045
67890  15630 10    3-tasks           probing    cifar-stage-1-4          0.000308
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4   0.001294
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4   0.000049
...                                                                           ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3      0.000187
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3      0.640480
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4      0.000280
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4      0.000148
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4      0.000120

                                                                              LR  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4         0.000245
12345  15630 10    3-tasks           probing    cifar-stage-1-4         0.000245
67890  15630 10    3-tasks           probing    cifar-stage-1-4         0.000245
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4  0.000024
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4  0.000024
...                                                                          ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     0.000024
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     0.000024
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     0.000024
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     0.000024
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     0.000024

                                                                            Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4         2.225916
12345  15630 10    3-tasks           probing    cifar-stage-1-4         1.993211
67890  15630 10    3-tasks           probing    cifar-stage-1-4         2.134570
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4  1.167756
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4  1.180475
...                                                                          ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     1.887241
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     1.907907
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     2.094614
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     2.000613
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     2.172788

                                                                        Time/Img Per Sec  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4              5236.252867
12345  15630 10    3-tasks           probing    cifar-stage-1-4              8866.044496
67890  15630 10    3-tasks           probing    cifar-stage-1-4              7748.217799
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4       5508.932100
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4       5883.742522
...                                                                                  ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3          5868.186828
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3          5127.977440
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4          8132.342401
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4          9124.368863
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4          7899.054682

                                                                            GPU Mem  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4          869.673340
12345  15630 10    3-tasks           probing    cifar-stage-1-4                 NaN
67890  15630 10    3-tasks           probing    cifar-stage-1-4          869.673340
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4  6502.318848
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4          NaN
...                                                                             ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     6488.273926
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     6488.273926
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     6489.509766
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     6489.509766
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     6489.509766

                                                                            Proc Mem  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4          3991.121094
12345  15630 10    3-tasks           probing    cifar-stage-1-4                  NaN
67890  15630 10    3-tasks           probing    cifar-stage-1-4          4115.968750
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4  18341.554688
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4           NaN
...                                                                              ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     16894.289062
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     16865.246094
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     14677.957031
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     13143.097656
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     13163.015625

                                                                        cifar100/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                   2.794480
12345  15630 10    3-tasks           probing    cifar-stage-1-4                   2.922263
67890  15630 10    3-tasks           probing    cifar-stage-1-4                   2.815243
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4            1.843304
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4            1.868889
...                                                                                    ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3               2.678399
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3               2.649088
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4               3.067034
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4               2.799995
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4               3.117944

                                                                        fer2013/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                  1.566038
12345  15630 10    3-tasks           probing    cifar-stage-1-4                  1.733587
67890  15630 10    3-tasks           probing    cifar-stage-1-4                  1.622464
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4           1.480987
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4           1.417946
...                                                                                   ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                   NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                   NaN
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                   NaN
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                   NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                   NaN

                                                                        resisc45/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                   2.317231
12345  15630 10    3-tasks           probing    cifar-stage-1-4                   1.323781
67890  15630 10    3-tasks           probing    cifar-stage-1-4                   1.966002
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4            0.907616
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4            0.977453
...                                                                                    ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3               1.096083
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3               1.166725
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4               1.122193
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4               1.201231
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4               1.227632

                                                                        cifar100/Accuracy  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                  0.437500
12345  15630 10    3-tasks           probing    cifar-stage-1-4                  0.500000
67890  15630 10    3-tasks           probing    cifar-stage-1-4                  0.562500
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4           0.511719
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4           0.500000
...                                                                                   ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3              0.362500
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3              0.400000
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4              0.250000
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4              0.350000
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4              0.250000

                                                                        ...  \
seed   Step  Epoch Task Type         Model Type Stitch Method           ...
111213 15630 10    3-tasks           probing    cifar-stage-1-4         ...
12345  15630 10    3-tasks           probing    cifar-stage-1-4         ...
67890  15630 10    3-tasks           probing    cifar-stage-1-4         ...
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4  ...
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4  ...
...                                                                     ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     ...
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3     ...
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     ...
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     ...
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4     ...

                                                                        Overall/Train fmow/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                                  NaN
12345  15630 10    3-tasks           probing    cifar-stage-1-4                                  NaN
67890  15630 10    3-tasks           probing    cifar-stage-1-4                                  NaN
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4                           NaN
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4                           NaN
...                                                                                              ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                              NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                              NaN
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                              NaN
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                              NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                              NaN

                                                                        Overall/Train sun397/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                                    NaN
12345  15630 10    3-tasks           probing    cifar-stage-1-4                                    NaN
67890  15630 10    3-tasks           probing    cifar-stage-1-4                                    NaN
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4                             NaN
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4                             NaN
...                                                                                                ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                                NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                                NaN
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                                NaN
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                                NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                                NaN

                                                                        Overall/Train dtd/Accuracy  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                                NaN
12345  15630 10    3-tasks           probing    cifar-stage-1-4                                NaN
67890  15630 10    3-tasks           probing    cifar-stage-1-4                                NaN
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4                         NaN
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4                         NaN
...                                                                                            ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                            NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                            NaN
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                            NaN
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                            NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                            NaN

                                                                        Overall/Train flowers/Accuracy  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                                    NaN
12345  15630 10    3-tasks           probing    cifar-stage-1-4                                    NaN
67890  15630 10    3-tasks           probing    cifar-stage-1-4                                    NaN
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4                             NaN
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4                             NaN
...                                                                                                ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                                NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                                NaN
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                                NaN
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                                NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                                NaN

                                                                        Overall/Train fmow/Accuracy  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                                 NaN
12345  15630 10    3-tasks           probing    cifar-stage-1-4                                 NaN
67890  15630 10    3-tasks           probing    cifar-stage-1-4                                 NaN
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4                          NaN
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4                          NaN
...                                                                                             ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                             NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                             NaN
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                             NaN
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                             NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                             NaN

                                                                        Overall/Train sun397/Accuracy  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                                   NaN
12345  15630 10    3-tasks           probing    cifar-stage-1-4                                   NaN
67890  15630 10    3-tasks           probing    cifar-stage-1-4                                   NaN
111213 10240 10    4-tasks           probing    cifar+resisc-stage-1-4                            NaN
12345  10240 10    4-tasks           probing    cifar+resisc-stage-1-4                            NaN
...                                                                                               ...
       1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                               NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-3                               NaN
111213 1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                               NaN
12345  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                               NaN
67890  1960  10    cifar-resisc-only resisc     rand+resisc-stage-4                               NaN

                                                                        Overall/dtd/Test Accuracy  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 15630 10    3-tasks           probing    cifar-stage-1-4                               NaN

In [8]:
final_df.loc[final_df.index.get_level_values("Stitch Method").str.contains("/")]

                                                                                                    Time/Data  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                              0.000295
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                              0.000045
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                              0.000394
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                         0.000820
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                         0.069876
...                                                                                                       ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                            0.000047
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                            0.000204
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...   0.000222
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...   0.000050
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...   0.000239

                                                                                                          LR  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             0.000245
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             0.000245
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             0.000245
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                        0.000024
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                        0.000024
...                                                                                                      ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                           0.000027
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                           0.000027
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  0.000024
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  0.000024
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  0.000024

                                                                                                        Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             2.393059
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             2.629872
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             2.614936
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                        1.813976
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                        1.889724
...                                                                                                      ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                           2.003898
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                           1.793679
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  1.528255
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  1.491569
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  1.330836

                                                                                                    Time/Img Per Sec  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                  4682.218735
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                  8339.876954
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                  5796.534266
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                             4765.702370
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                             4739.452561
...                                                                                                              ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                               11139.721318
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                               10845.084104
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...       5415.832016
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...       5428.536765
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...       5350.121270

                                                                                                        GPU Mem  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                              871.670898
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                     NaN
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                              871.670898
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                         900.406250
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                         900.406250
...                                                                                                         ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                   NaN
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                           6486.527344
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  6537.900391
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...          NaN
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  6537.900391

                                                                                                        Proc Mem  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                              4404.320312
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                      NaN
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                              4305.992188
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                         5325.312500
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                         5384.359375
...                                                                                                          ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                    NaN
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                           15117.339844
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  15465.007812
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...           NaN
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  16786.019531

                                                                                                    cifar100/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       2.822231
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       2.891679
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       1.987031
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                  2.020121
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                  2.304247
...                                                                                                                ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                     2.399248
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                     2.037240
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            2.000716
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            1.952896
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            1.684089

                                                                                                    fer2013/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                      1.490243
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                      1.525356
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                      1.478839
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                 1.458595
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                 1.560069
...                                                                                                               ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                         NaN
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                         NaN
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                NaN
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                NaN
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                NaN

                                                                                                    resisc45/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       2.025339
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       2.822393
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       2.001424
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                  0.985925
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                  1.140808
...                                                                                                                ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                     1.608549
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                     1.550117
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            1.055793
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            1.030241
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            0.977584

                                                                                                    cifar100/Accuracy  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       0.50000
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       0.46875
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                       0.43750
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                  0.43750
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                  0.46875
...                                                                                                               ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                     0.42500
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                     0.50000
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            0.45000
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            0.51250
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...            0.58750

                                                                                                    ...  \
seed   Step  Epoch Task Type         Model Type Stitch Method                                       ...
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             ...
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             ...
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                             ...
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                        ...
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                        ...
...                                                                                                 ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                           ...
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                           ...
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  ...
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  ...
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...  ...

                                                                                                    Overall/Train fmow/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                      NaN
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                      NaN
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                      NaN
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                            2.758223
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                            2.755584
...                                                                                                                          ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                                    NaN
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                                    NaN
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                           NaN
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                           NaN
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                           NaN

                                                                                                    Overall/Train sun397/Main Loss  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                        NaN
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                        NaN
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                        NaN
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                              2.175015
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                              2.168432
...                                                                                                                            ...
       5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                                      NaN
67890  5880  30    cifar-resisc-only probing    cifar-stage-1-4/epochs-30                                                      NaN
111213 1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                             NaN
12345  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                             NaN
67890  1960  10    cifar-resisc-only cifar      cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-s...                             NaN

                                                                                                    Overall/Train dtd/Accuracy  \
seed   Step  Epoch Task Type         Model Type Stitch Method
111213 23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                    NaN
12345  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                    NaN
67890  23680 10    4-tasks           probing    cifar-stage-1-4/no-pcam                                                    NaN
111213 24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                          0.683023
12345  24020 10    8-tasks           probing    cifar+resisc-stage-1-4/bs-32                                          0.687540
...                                                                                                                        ...

# Summaries

In [9]:
group_cols = list(set(final_df.index.names) - {"seed"})
groupby = final_df.groupby(group_cols)
run_avgs = groupby.mean()
run_stds = groupby.std()

In [10]:
def get_group(df, task_type, imported_stages):
    task_types = df.index.get_level_values("Task Type")
    first_stage = df.index.get_level_values("Stitch Method").str.extract(r'(stage-\d+(?:-\d+)?)', expand=False)
    return df.loc[(task_types == task_type) & (first_stage == imported_stages)]


STITCH_METHOD_ORDER = ("cifar+rand", "rand+resisc", "cifar+resisc")

def sort_stitch_methods(df, order=STITCH_METHOD_ORDER):
    """ Within each Task Type x Model Type group, sorts rows by `order` instead of alphabetically. """
    def stitch_sort_key(idx):
        if idx.name != "Stitch Method":
            return idx
        prefix = idx.str.extract(r'^(.+?)-stage', expand=False)
        return pd.Index(pd.Categorical(prefix, categories=order, ordered=True), name=idx.name)
    return df.sort_index(level=["Task Type", "Model Type", "Stitch Method"], key=stitch_sort_key, sort_remaining=False)


TASKMAP = {
    "cifar-resisc-only": ["cifar100", "resisc45"],
    "4-tasks": ["cifar100", "fer2013", "pcam", "resisc45"],
    "8-tasks": ["cifar100", "dtd", "fer2013", "flowers", "food101", "fmow", "resisc45", "sun397"],
    "9-tasks": ["cifar100", "dtd", "fer2013", "flowers", "food101", "fmow", "pcam", "resisc45", "sun397"],
}

def filter_scores(df, task_type, imported_stages):
    df = sort_stitch_methods(get_group(df, task_type, imported_stages))
    cols = [f"Overall/{t}/Test Accuracy" for t in TASKMAP[task_type]]
    return df[cols]


def print_scores(avg_df, std_df, task_type, imported_stages, include_index=False):
    avg_scores = filter_scores(avg_df, task_type, imported_stages) * 100.0
    std_scores = filter_scores(std_df, task_type, imported_stages) * 100.0
    # Human-readable "avg (std)" string formatting. Handy for future LaTeX tables, but for Google Sheets we need each
    # value in a separate cell so it can be treated as numeric data.
    # formatted = avg_scores.combine(std_scores, lambda avg_col, std_col: pd.Series(
    #     [f"{avg * 100:.1f} ({std * 100:.1f})" for avg, std in zip(avg_col, std_col)], index=avg_col.index))
    # print(formatted.to_csv(sep="\t", index=False))
    interleaved = {}
    for col in avg_scores.columns:
        interleaved[col] = avg_scores[col]
        interleaved[f"{col} (std)"] = std_scores[col]
    print(pd.DataFrame(interleaved).to_csv(sep="\t", index=include_index))

In [11]:
print_scores(run_avgs, run_stds, "8-tasks", "stage-1-4", include_index=True)

Stitch Method	Model Type	Epoch	Step	Task Type	Overall/cifar100/Test Accuracy	Overall/cifar100/Test Accuracy (std)	Overall/dtd/Test Accuracy	Overall/dtd/Test Accuracy (std)	Overall/fer2013/Test Accuracy	Overall/fer2013/Test Accuracy (std)	Overall/flowers/Test Accuracy	Overall/flowers/Test Accuracy (std)	Overall/food101/Test Accuracy	Overall/food101/Test Accuracy (std)	Overall/fmow/Test Accuracy	Overall/fmow/Test Accuracy (std)	Overall/resisc45/Test Accuracy	Overall/resisc45/Test Accuracy (std)	Overall/sun397/Test Accuracy	Overall/sun397/Test Accuracy (std)
cifar+resisc-stage-1-4	probing	10	3010	8-tasks	48.60666666666666	0.08144527815246788	35.319148936170215	0.24375402632743956	46.354602024705116	0.20108326455475994	50.7399577167019	0.3415189461701093	28.724752475247524	0.09757374253271232	24.553706049092337	0.05972288257746265	73.84126984126983	0.34375250520170864	22.021830394626367	0.1389125565584118
cifar+resisc-stage-1-4/bs-32	probing	10	24020	8-tasks	49.68	0.22605309110914837	34.255319148936174	0.3321807445956607	48.16569146466054	0.0804333058219075	49.796714912993984	0.21879369079644892	30.4	0.003960396039603964	24.957783004643872	0.041042933444350414	74.91534391534391	0.18259718440992112	21.24769101595298	0.09589448554337006
cifar+resisc-stage-1-4/bs-32/unfrozen	probing	10	24020	8-tasks	53.37666666666666	0.5435377938408092	45.283687943262414	0.5687593947640224	57.5740689142751	0.21687181998394367	58.17206049764189	0.18327252674555766	42.563696369636965	0.39632333071088754	30.67517037573126	0.22344730456725892	79.42328042328043	0.23400364431212364	27.469353484466836	0.22087869983934924
cifar+resisc-stage-1-4/unfrozen	probing	10	3010	8-tasks	51.63666666666666	0.514328040586293	43.38652482269503	0.7063327761362437	54.922448221417284	0.6608759879387716	57.53781102618313	0.4253275924742927	38.28514851485149	0.1432328025348526	29.110126047886137	0.15520305448956911	77.0	0.4024991216859027	26.70864819479429	0.01267814346812658
cifar-stage-1-4	probing	10	24020	8-tasks	45.233333333333334	0.20647840887931093	26.063829787234045	0.10638297872340371	45.30974273242314	0.20866204085317058	41.61110207621836	0.19605509101778248	22.99009900990099	0.4283823297580981	19.870635064230143	0.2507447358700062	55.70370370370371	0.18533629511255595	16.384550797649034	0.21787078384496336
cifar-stage-1-4/bs-256-lr-0.001	probing	10	3010	8-tasks	46.86	0.07211102550927762	31.329787234042556	0.3235511984201202	43.40577691093155	0.06282042007276091	44.04510218463707	0.29557772819895883	23.728052805280527	0.09391512296677179	19.593209094747	0.042990704509327446	55.529100529100525	0.28497847639143453	18.599496221662466	0.10898391764626696
cifar-stage-1-4/bs-256-lr-0.001/unfrozen	probing	10	3010	8-tasks	49.31	0.4484417464955717	41.95035460992908	0.6942117712926177	53.08349586700102	0.3846528910537519	53.49379302867675	0.34126070874477427	33.64224422442244	0.06152438388240841	26.62233882154273	0.177639550875595	73.24867724867725	0.24037707283811313	25.04450041981528	0.18784470450787497
cifar-stage-1-4/unfrozen	probing	10	24020	8-tasks	43.57	7.964590384947616	36.40070921985816	6.538083002656843	53.35748119253273	5.490850183986778	46.82062123922589	9.47389118078369	31.118151815181516	8.929309311544236	25.615161932332185	4.056699207318462	68.23280423280423	11.444084855911392	20.119227539882452	4.8444262003172325
resisc-stage-1-4	probing	10	24020	8-tasks	29.903333333333332	0.17387735140993144	23.865248226950353	0.7547445621912326	44.1209250487601	0.41397765277524656	36.547948175855154	0.23529608515434278	19.46534653465347	0.26734873396812175	20.83107170858211	0.252263264427217	69.92063492063492	0.3897787034225002	12.866498740554155	0.14842236637437078
resisc-stage-1-4/bs-256-lr-0.001	probing	10	3010	8-tasks	29.406666666666663	0.3329164059239689	27.570921985815605	0.1625026842182944	41.98941209250488	0.18217744261106386	37.78392150485173	0.14756499798141923	19.93795379537954	0.07187145921487076	22.33882154272963	0.03846978717258491	70.26984126984127	0.2670254577977909	14.354324097397145	0.1804014212452292
resisc-stage-1-4/bs-256-lr-0.001/unfrozen	probing	10	3010	8-tasks	43.3	0.2128379665379296	38.156028368794324	0.47674927871449657	53.45964521222254	0.6536412486268407	50.96763701414865	0.2821491555195491	30.781518151815177	0.3692808279647037	26.652493818225683	0.14708097700086992	72.28042328042328	0.07331431989709764	23.178841309823675	0.08107545057647884
resisc-stage-1-4/unfrozen	probing	10	24020	8-tasks	49.00666666666667	0.8137772012862825	41.187943262411345	0.3847967094718218	57.05860499674933	0.7144995182979912	54.67013606548491	1.284693128606787	37.85478547854786	1.8745535254679888	28.178336650382967	0.9267070087506938	75.0	1.145939406208255	23.909319899244334	0.39336669453481027

# Sandbox

In [14]:
290 * .73

211.7

In [77]:
# Find missing results.
for cfgfile in tqdm(list(sorted(proj_dir.rglob("config.yml")))):
    result_files = list(cfgfile.parent.glob("result*.pkl"))
    if not result_files:
        print(f"Missing: {cfgfile.parent}")

100%|██████████| 1831/1831 [00:00<00:00, 53052.84it/s]

Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,6-adapter-finetune
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-3,6-adapter-finetune
Missing: ../experiments/across-scales/mobilenet-v3-lr-2.0e-4/train-mobilenet-v3-lr-2.0e-4-gap-1,6-adapter-finetune
Missing: ../experiments/across-scales/mobilenet-v3-lr-2.0e-4/train-mobilenet-v3-lr-2.0e-4-gap-3,6-adapter-finetune
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,2-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,4-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,1-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,1-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,1-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,1-adapter-finetune
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-finetune
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-finetune
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,6-adapter-finetune
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-3,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-3,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-3,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-3,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s-bert-token-ones/train-resnet-50-vit-s-gap-1,1-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s-bert-token-ones/train-resnet-50-vit-s-gap-1,1-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s-bert-token-ones/train-resnet-50-vit-s-gap-1,1-adapter-bottleneck_no_downsample

In [9]:
# Rename result.pkl to result-12345.pkl.
for cfgfile in tqdm(list(sorted(proj_dir.rglob("config.yml")))):
    result_files = list(cfgfile.parent.glob("result.pkl"))
    if len(result_files) == 1:
        f = result_files[0]
        newfile = f.parent / (f.stem + '-12345.pkl')
        if newfile.is_file():
            print(f"WARNING: {newfile} already exists; skipping.")
            continue
        print(f"Renaming: {newfile}")
        f.replace(newfile)
    if len(result_files) > 1:
        print(f"WARNING: {cfgfile.parent} matched more than one file: {result_files}")

100%|██████████| 74/74 [00:00<00:00, 9445.19it/s]

Renaming: ../experiments/moe/conv4/multitask/3-tasks/probing/cifar-stage-1-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/probing/cifar+resisc-stage-1-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/probing/cifar-stage-1-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/probing/cifar-stage-1-4/no-pcam/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/probing/resisc-stage-1-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+rand-stage-1-2-cifar-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+rand-stage-1-3-cifar-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+rand-stage-2-3-cifar-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+rand-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+rand-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+resisc-stage-1-2-cifar-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+resisc-stage-1-3-cifar-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+resisc-stage-2-3-cifar-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+resisc-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/cifar+resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/rand+resisc-stage-1-2-cifar-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/rand+resisc-stage-1-3-cifar-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/rand+resisc-stage-2-3-cifar-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/rand+resisc-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-cifar/rand+resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+rand-stage-1-2-resisc-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+rand-stage-1-3-resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+rand-stage-2-3-resisc-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+rand-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+rand-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+resisc-stage-1-2-resisc-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+resisc-stage-1-3-resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+resisc-stage-2-3-resisc-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+resisc-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/cifar+resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/rand+resisc-stage-1-2-resisc-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/rand+resisc-stage-1-3-resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/rand+resisc-stage-2-3-resisc-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/rand+resisc-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/4-tasks/stitch-into-resisc/rand+resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/probing/cifar+resisc-stage-1-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/probing/cifar-stage-1-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/probing/cifar-stage-1-4/epochs-30/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/probing/resisc-stage-1-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+rand-stage-1-2-cifar-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+rand-stage-2-3-cifar-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+rand-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+rand-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+resisc-stage-1-2-cifar-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+resisc-stage-1-3-cifar-stage-4/unfreeze-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+resisc-stage-2-3-cifar-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+resisc-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/cifar+resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/rand+resisc-stage-1-2-cifar-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/rand+resisc-stage-2-3-cifar-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/rand+resisc-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-cifar/rand+resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+rand-stage-1-2-resisc-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+rand-stage-1-3-resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+rand-stage-2-3-resisc-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+rand-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+rand-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+resisc-stage-1-2-resisc-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+resisc-stage-1-3-resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+resisc-stage-2-3-resisc-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+resisc-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/cifar+resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/rand+resisc-stage-1-2-resisc-stage-3-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/rand+resisc-stage-1-3-resisc-stage-4/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/rand+resisc-stage-2-3-resisc-stage-1-2/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/rand+resisc-stage-3/result-12345.pkl
Renaming: ../experiments/moe/conv4/multitask/cifar-resisc-only/stitch-into-resisc/rand+resisc-stage-4/result-12345.pkl