# Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import warnings
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import torch
from torchtnt.utils.flops import FlopTensorDispatchMode
from tqdm import tqdm

from utils import num_params
from utils.postprocess import load_result_dataframe, last_epoch_only

W0326 10:43:00.317000 11251 site-packages/torch/distributed/elastic/multiprocessing/redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.

In [3]:
sns.set(font_scale=1.25, style="whitegrid")

# Ignore known warnings that come when constructing subnets.
warnings.filterwarnings("ignore", message=".*The parameter 'pretrained' is deprecated.*")
warnings.filterwarnings("ignore", message=".*Arguments other than a weight enum.*")
warnings.filterwarnings("ignore", message=".*already erased node.*")

# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
# print(f"Using device = {device}")

NUM_CORES = os.cpu_count()
if hasattr(os, "sched_getaffinity"):
    # This function is only available on certain platforms. When running with Slurm, it can tell us the true
    # number of cores we have access to.
    NUM_CORES = len(os.sched_getaffinity(0))
print (f"Using {NUM_CORES} cores.")

Using 8 cores.

# Scan Files

Find and load all result files.

In [7]:
project_name = "moe"
proj_dir = Path("../experiments") / project_name
full_df = load_result_dataframe(proj_dir, calc_sizes=False)

100%|██████████| 21/21 [00:00<00:00, 2211.69it/s]

Filter down to just the final performance: i.e., the last epoch number.

In [8]:
final_df = last_epoch_only(full_df)

Remap to more presentable names.

In [9]:
# First just reset the whole index so we can use them as columns.
final_df.drop(columns="Step", inplace=True)  # This column is duplicated, delete one of them.
final_df.reset_index(inplace=True)

column_name_remap = {
    "arch": "Architecture",
    "adapter": "Adapter",
    "seed": "Seed",
    "num_params": "# params",
    "num_trainable_params": "# trainable params",
    "num_flops": "# FLOPs",
    "Overall/Train Loss": "Train Loss",
    "Overall/Train Accuracy": "Train Accuracy",
    "Overall/Test Accuracy": "Test Accuracy",
}
final_df.rename(columns=column_name_remap, inplace=True)

# Set a new, clean index.
final_df.set_index(["Architecture", "Seed", "Epoch", "Step"], inplace=True)
final_df

/var/folders/hh/f20wzr451rd3m04552cf7n4r0000gp/T/ipykernel_11251/200306417.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns="Step", inplace=True)  # This column is duplicated, delete one of them.
/var/folders/hh/f20wzr451rd3m04552cf7n4r0000gp/T/ipykernel_11251/200306417.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.rename(columns=column_name_remap, inplace=True)

                                                          dataset  Time/Data  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320        cars   0.000070
                                                  1960   cifar100   0.000034
                                                  150         dtd   0.000073
                                                  1130    fer2013   0.000036
                                                  40      flowers   0.000065
                                                  3010       fmow   0.000064
                                                  2960    food101   0.000034
                                                  2350      mnist   0.000035
                                                  10240      pcam   0.000096
                                                  740    resisc45   0.000035
                                                  780      sun397   0.000038
stitch-all-stages-resnet-cifar-resisc 12345 10    320        cars   0.000069
                                                  1960   cifar100   0.000116
                                                  150         dtd   0.000128
                                                  1130    fer2013   0.000052
                                                  40      flowers   0.000084
                                                  2960    food101   0.000063
                                                  2350      mnist   0.000067
                                                  10240      pcam   0.000065
                                                  740    resisc45   0.000092
                                                  780      sun397   0.000046

                                                               LR      Loss  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320    0.000049  3.156945
                                                  1960   0.000049  0.056158
                                                  150    0.000049  1.612287
                                                  1130   0.000049  1.089502
                                                  40     0.000049  1.426029
                                                  3010   0.000049  2.454371
                                                  2960   0.000049  2.531636
                                                  2350   0.000049  0.077128
                                                  10240  0.000049  0.267105
                                                  740    0.000049  0.049373
                                                  780    0.000049  2.198368
stitch-all-stages-resnet-cifar-resisc 12345 10    320    0.000005  2.794657
                                                  1960   0.000005  0.672788
                                                  150    0.000005  1.695499
                                                  1130   0.000005  0.853150
                                                  40     0.000005  2.185804
                                                  2960   0.000005  1.185809
                                                  2350   0.000005  0.007936
                                                  10240  0.000005  0.188536
                                                  740    0.000005  0.534915
                                                  780    0.000005  1.721149

                                                         Time/Img Per Sec  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320         2264.566620
                                                  1960        1924.169190
                                                  150         2202.404406
                                                  1130        1487.925017
                                                  40          2335.038701
                                                  3010        1757.903996
                                                  2960        2336.331386
                                                  2350        2024.644422
                                                  10240       2345.899858
                                                  740         2283.130185
                                                  780         2171.730484
stitch-all-stages-resnet-cifar-resisc 12345 10    320          386.151903
                                                  1960         350.246988
                                                  150          375.397929
                                                  1130         304.741673
                                                  40           392.135876
                                                  2960         387.005715
                                                  2350         360.109167
                                                  10240        395.615578
                                                  740          385.979119
                                                  780          374.611161

                                                              Max Mem  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320     1471.835938
                                                  1960     769.786133
                                                  150     1291.377930
                                                  1130     536.994629
                                                  40      1708.139160
                                                  3010     681.001953
                                                  2960    1588.087891
                                                  2350     854.007812
                                                  10240   1726.504395
                                                  740     1487.681641
                                                  780     1099.526855
stitch-all-stages-resnet-cifar-resisc 12345 10    320    24668.621582
                                                  1960   10493.782715
                                                  150    21096.351074
                                                  1130    5856.515137
                                                  40     29580.114746
                                                  2960   27117.702637
                                                  2350   12251.855957
                                                  10240  30040.827637
                                                  740    25104.972168
                                                  780    16912.243652

                                                         Accuracy  Time/Step  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320    0.326923   0.045995
                                                  1960   1.000000   0.020822
                                                  150    0.534091   0.040029
                                                  1130   0.631579   0.012805
                                                  40     0.746032   0.054025
                                                  3010   0.375000   0.018267
                                                  2960   0.382609   0.049256
                                                  2350   1.000000   0.023742
                                                  10240  0.906250   0.054659
                                                  740    1.000000   0.046462
                                                  780    0.362319   0.031810
stitch-all-stages-resnet-cifar-resisc 12345 10    320    0.346154   0.269393
                                                  1960   0.750000   0.114320
                                                  150    0.511364   0.234546
                                                  1130   0.736842   0.062400
                                                  40     0.500000   0.321401
                                                  2960   0.678261   0.297216
                                                  2350   1.000000   0.133359
                                                  10240  0.914062   0.323611
                                                  740    0.839623   0.274718
                                                  780    0.579710   0.184237

                                                         Train Loss  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320      2.920632
                                                  1960     0.177376
                                                  150      1.401915
                                                  1130     1.193963
                                                  40       1.461771
                                                  3010     2.146150
                                                  2960     2.349059
                                                  2350     0.095648
                                                  10240    0.283109
                                                  740      0.077285
                                                  780      2.114906
stitch-all-stages-resnet-cifar-resisc 12345 10    320      2.831321
                                                  1960     0.679994
                                                  150      1.946635
                                                  1130     0.950266
                                                  40       2.274809
                                                  2960     1.345942
                                                  2350     0.020387
                                                  10240    0.126628
                                                  740      0.512809
                                                  780      1.628982

                                                         Train Accuracy  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320          0.367019
                                                  1960         0.952260
                                                  150          0.605053
                                                  1130         0.551237
                                                  40           0.750980
                                                  3010         0.427027
                                                  2960         0.426007
                                                  2350         0.969467
                                                  10240        0.881672
                                                  740          0.976614
                                                  780          0.497280
stitch-all-stages-resnet-cifar-resisc 12345 10    320          0.345285
                                                  1960         0.804800
                                                  150          0.454255
                                                  1130         0.641344
                                                  40           0.448039
                                                  2960         0.643208
                                                  2350         0.993667
                                                  10240        0.953060
                                                  740          0.839577
                                                  780          0.585743

                                                         Test Accuracy  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320         0.177816
                                                  1960        0.746300
                                                  150         0.501596
                                                  1130        0.550850
                                                  40          0.542276
                                                  3010        0.337208
                                                  2960        0.508079
                                                  2350        0.981700
                                                  10240       0.820709
                                                  740         0.918571
                                                  780         0.337481
stitch-all-stages-resnet-cifar-resisc 12345 10    320         0.134419
                                                  1960        0.711500
                                                  150         0.364894
                                                  1130        0.637643
                                                  40          0.311870
                                                  2960        0.641941
                                                  2350        0.992500
                                                  10240       0.855072
                                                  740         0.837302
                                                  780         0.307809

                                                          Time/Total  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320      85.016752
                                                  1960    135.921245
                                                  150      29.812942
                                                  1130     85.773899
                                                  40       32.202371
                                                  3010    222.739082
                                                  2960    332.986343
                                                  2350    157.109506
                                                  10240   640.971700
                                                  740      75.267999
                                                  780     438.293598
stitch-all-stages-resnet-cifar-resisc 12345 10    320     170.196795
                                                  1960    695.115067
                                                  150      76.510454
                                                  1130    410.762044
                                                  40       61.855276
                                                  2960   1111.392262
                                                  2350    820.145877
                                                  10240  3526.650820
                                                  740     288.265661
                                                  780     506.222320

                                                         Time/Per Epoch
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320          8.714122
                                                  1960        13.366419
                                                  150          2.680801
                                                  1130         8.372903
                                                  40           2.928472
                                                  3010        21.934146
                                                  2960        32.837780
                                                  2350        15.556456
                                                  10240       63.270406
                                                  740          6.293576
                                                  780         43.168706
stitch-all-stages-resnet-cifar-resisc 12345 10    320         16.530751
                                                  1960        68.983396
                                                  150          7.252493
                                                  1130        40.706560
                                                  40           5.981490
                                                  2960       110.896466
                                                  2350        81.793903
                                                  10240      349.712857
                                                  740         28.060174
                                                  780         50.526260

In [13]:
final_df[["dataset", "Train Accuracy", "Test Accuracy"]]

                                                          dataset  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320        cars
                                                  1960   cifar100
                                                  150         dtd
                                                  1130    fer2013
                                                  40      flowers
                                                  3010       fmow
                                                  2960    food101
                                                  2350      mnist
                                                  10240      pcam
                                                  740    resisc45
                                                  780      sun397
stitch-all-stages-resnet-cifar-resisc 12345 10    320        cars
                                                  1960   cifar100
                                                  150         dtd
                                                  1130    fer2013
                                                  40      flowers
                                                  2960    food101
                                                  2350      mnist
                                                  10240      pcam
                                                  740    resisc45
                                                  780      sun397

                                                         Train Accuracy  \
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320          0.367019
                                                  1960         0.952260
                                                  150          0.605053
                                                  1130         0.551237
                                                  40           0.750980
                                                  3010         0.427027
                                                  2960         0.426007
                                                  2350         0.969467
                                                  10240        0.881672
                                                  740          0.976614
                                                  780          0.497280
stitch-all-stages-resnet-cifar-resisc 12345 10    320          0.345285
                                                  1960         0.804800
                                                  150          0.454255
                                                  1130         0.641344
                                                  40           0.448039
                                                  2960         0.643208
                                                  2350         0.993667
                                                  10240        0.953060
                                                  740          0.839577
                                                  780          0.585743

                                                         Test Accuracy
Architecture                          Seed  Epoch Step
baseline-resnet-cifar-resisc          12345 10    320         0.177816
                                                  1960        0.746300
                                                  150         0.501596
                                                  1130        0.550850
                                                  40          0.542276
                                                  3010        0.337208
                                                  2960        0.508079
                                                  2350        0.981700
                                                  10240       0.820709
                                                  740         0.918571
                                                  780         0.337481
stitch-all-stages-resnet-cifar-resisc 12345 10    320         0.134419
                                                  1960        0.711500
                                                  150         0.364894
                                                  1130        0.637643
                                                  40          0.311870
                                                  2960        0.641941
                                                  2350        0.992500
                                                  10240       0.855072
                                                  740         0.837302
                                                  780         0.307809

In [10]:
print("Available architectures:")
for aname in sorted(final_df.index.get_level_values("Architecture").unique()):
    print(f"    {aname}")

Available architectures:
    baseline-resnet-cifar-resisc
    stitch-all-stages-resnet-cifar-resisc

# Plots

In [18]:

def savefig(figname):
    # plt.tight_layout()  # Does not play nicely with Seaborn's FacetGrid. Using bbox_inches instead.
    save_dir = proj_dir / "figures"
    save_dir.mkdir(parents=True, exist_ok=True)
    print(f"Saving plot: {save_dir}/{figname}.(pdf/png)")
    plt.savefig(save_dir / (figname + ".pdf"), bbox_inches="tight")
    plt.savefig(save_dir / (figname + ".png"), bbox_inches="tight")


def plot_accuracy(final_acc_df, src_stage=None, dest_stage=None, arch_choice=None, arch_col="Architecture",
                  adapter_choice=None, adapter_col="Adapter", name=None, save=True, **kwargs):
    # Filter down to chosen gaps.
    if src_stage:
        final_acc_df = final_acc_df.loc[final_acc_df.index.get_level_values("Src Stage") == src_stage]
    if dest_stage:
        final_acc_df = final_acc_df.loc[final_acc_df.index.get_level_values("Dest Stage") == dest_stage]

    # Interpret the choice parameters.
    if not arch_choice:
        arch_choice = DFLT_ARCHS
    elif isinstance(arch_choice, str):
        arch_choice = [arch_choice]
    if not adapter_choice:
        adapter_choice = DFLT_ADAPTERS
    elif isinstance(adapter_choice, str):
        adapter_choice = [adapter_choice]

    # Either filter down to one choice value, or tell Seaborn to plot them as hue/style.
    title = []
    if name:
        title.append(name)
    if len(arch_choice) == 1:
        final_acc_df = final_acc_df.loc[final_acc_df.index.get_level_values(arch_col) == arch_choice[0]]
        title.append(arch_choice[0])
    elif arch_col in final_acc_df.index.names:
        kwargs.setdefault("row", arch_col)
        kwargs.setdefault("row_order", arch_choice)
    src_name = str(src_stage) if src_stage else "All"
    dest_name = str(dest_stage) if dest_stage else "All"
    title.append(f"Stage {src_name} → {dest_name}")
    if len(adapter_choice) == 1:
        final_acc_df = final_acc_df.loc[final_acc_df.index.get_level_values(adapter_col) == adapter_choice[0]]
        title.extend(["-", adapter_choice[0]])
    elif adapter_col in final_acc_df.index.names:
        kwargs.setdefault("hue", adapter_col)
        kwargs.setdefault("hue_order", adapter_choice)
    title = " ".join(title)

    # Automatically prefer these palettes for a certain number of hue categories.
    if "hue" in kwargs:
        if "hue_order" in kwargs:
            # If the set of hues is defined, use that.
            num_hues = len(kwargs["hue_order"])
        else:
            # Otherwise, count the number of unique values in the hue column.
            huecol = (final_acc_df.index.get_level_values(kwargs["hue"]) if kwargs["hue"] in final_acc_df.index.names
                      else final_acc_df[kwargs["hue"]])
            num_hues = len(huecol.unique())
        if num_hues > 20:
            kwargs.setdefault("palette", "magma")
        elif num_hues >= 10:  # FIXME: temporary "=", until I make manual color assignments
            kwargs.setdefault("palette", "tab20")

    # Try to intelligently select which kind based on the x-axis type.
    orig_x = None
    orig_y = orig_arch_acc.get(arch_choice[0]) if len(arch_choice) == 1 else None
    if "x" not in kwargs:
        kwargs["x"] = "Dest Stage"
    if kwargs["x"] == "Dest Stage" or kwargs["x"] == "num_downsamples":
        kwargs.setdefault("kind", "line")
        xvar = "Depth"
    elif "params" in kwargs["x"].lower():
        kwargs.setdefault("kind", "line")
        kwargs.setdefault("linestyle", ":")
        xvar = "Size"
        if len(arch_choice) == 1:
            orig_x = orig_arch_params.get(arch_choice[0])
    elif "flops" in kwargs["x"].lower():
        kwargs.setdefault("kind", "line")
        kwargs.setdefault("linestyle", ":")
        xvar = "FLOPs"
        if len(arch_choice) == 1:
            orig_x = orig_arch_flops.get(arch_choice[0])
    else:
        xvar = kwargs["x"]

    # Insert some other styling recommendations.
    if kwargs.get("kind") == "line":
        # Add markers to lines (if not already configured).
        kwargs.setdefault("marker", "o")
        kwargs.setdefault("markersize", 6)
        kwargs.setdefault("errorbar", "sd")
    kwargs.setdefault("facet_kws", {}).setdefault("legend_out", True)

    # Finally... plot!
    fg = sns.relplot(final_acc_df.reset_index(), y="Test Accuracy", **kwargs)
    if not kwargs.get("row") and not kwargs.get("col"):
        ax = fg.ax
        ax.set_title(title)
        # If we only have one axes, add some info about this particular model.
        if orig_y is not None:
            if orig_x is not None:
                # Plot a point representing the original model.
                ax.scatter(orig_x, orig_y, c="grey", s=100, marker="*", zorder=100)
            else:
                # Plot a horizontal line representing the original model.
                ax.axhline(orig_y, color="grey", linestyle="--")
        # And optionally save.
        if save:
            savefig(f"{title.replace(' ', '-').replace('→', 'to')}-acc-vs-{xvar}".lower())
        return ax
    else:
        return fg


def plot_accuracy_vs_depth(final_acc_df, **kwargs):
    return plot_accuracy(final_acc_df, x="Dest Stage", **kwargs)


def plot_accuracy_vs_size(final_acc_df, **kwargs):
    if "# params" not in final_acc_df.index.names and "# params" not in final_acc_df.columns:
        return None
    return plot_accuracy(final_acc_df, x="# params", **kwargs)


def plot_accuracy_vs_flops(final_acc_df, **kwargs):
    if "# FLOPs" not in final_acc_df.index.names and "# FLOPs" not in final_acc_df.columns:
        return None
    return plot_accuracy(final_acc_df, x="# FLOPs", **kwargs)


def main_plots(arch_choice, **kwargs):
    plot_accuracy_vs_depth(best_of_lrs, src_stage=current_src_stage, arch_choice=arch_choice, **kwargs)
    plot_accuracy_vs_size(best_of_lrs, src_stage=current_src_stage, arch_choice=arch_choice, **kwargs)
    plot_accuracy_vs_flops(best_of_lrs, src_stage=current_src_stage, arch_choice=arch_choice, **kwargs)

# Sandbox

In [68]:
final_df.loc[
    final_df.index.get_level_values("Architecture").str.fullmatch(f"ViT-S") &
    final_df.index.get_level_values("Adapter").str.fullmatch(f".*Block.*") #&
    # (final_df.index.get_level_values("first_deleted_block") == 5)
]

                                                                                         first_deleted_block  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S                        1
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S                        1
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S                        1
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S                        1
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S                        1
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S                        1
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S                        1
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S                        1
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S                        3
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S                        3
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S                        3
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S                        3
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S                        3
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S                        3
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S                        5
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S                        5
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S                        5
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S                        5

                                                                                         last_deleted_block  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S                       1
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S                       1
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S                       2
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S                       2
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S                       4
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S                       4
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S                       6
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S                       6
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S                       3
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S                       3
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S                       4
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S                       4
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S                       6
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S                       6
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S                       5
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S                       5
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S                       6
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S                       6

                                                                                         num_downsamples  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S                    0
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S                    0
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S                    1
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S                    1
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S                    2
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S                    2
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S                    3
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S                    3
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S                    0
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S                    0
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S                    1
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S                    1
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S                    2
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S                    2
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S                    0
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S                    0
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S                    1
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S                    1

                                                                                            # FLOPs  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S      3892632576
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S      3892632576
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S      3544046592
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S      3544046592
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S      2846874624
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S      2846874624
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S      2149702656
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S      2149702656
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S      3892632576
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S      3892632576
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S      3544046592
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S      3544046592
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S      2846874624
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S      2846874624
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S      3892632576
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S      3892632576
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S      3544046592
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S      3544046592

                                                                                         # params  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S      20276200
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S      20276200
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S      18501736
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S      18501736
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S      14952808
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S      14952808
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S      11403880
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S      11403880
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S      20276200
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S      20276200
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S      18501736
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S      18501736
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S      14952808
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S      14952808
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S      20276200
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S      20276200
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S      18501736
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S      18501736

                                                                                         # trainable params  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S                 1774464
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S                 1774464
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S                 1774464
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S                 1774464
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S                 3548928
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S                 3548928
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S                 5323392
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S                 5323392
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S                 1774464
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S                 1774464
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S                 1774464
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S                 1774464
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S                 3548928
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S                 3548928
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S                 1774464
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S                 1774464
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S                 1774464
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S                 1774464

                                                                                         Time/Data  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S       0.000046
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S       0.000039
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S       0.000052
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S       0.000054
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S       0.000086
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S       0.000065
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S       0.000093
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S       0.000080
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S       0.000149
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S       0.000062
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S       0.001107
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S       0.000083
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S       0.000082
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S       0.000080
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S       0.000090
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S       0.000075
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S       0.000096
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S       0.000042

                                                                                               LR  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S      0.000049
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S      0.000049
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S      0.000049
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S      0.000049
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S      0.000049
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S      0.000049
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S      0.000049
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S      0.000049
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S      0.000049
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S      0.000049

                                                                                             Loss  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S      0.708422
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S      0.876882
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S      0.811840
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S      0.753565
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S      1.073764
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S      1.369294
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S      2.425477
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S      1.687816
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S      0.685000
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S      0.758140
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S      0.954206
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S      0.957681
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S      1.299624
             Downsample, BasicBlock    2         4          12345 10    25030 ViT-S      1.332993
             No Downsample, BasicBlock 3         3          12345 10    25030 ViT-S      1.153609
             Downsample, BasicBlock    3         3          12345 10    25030 ViT-S      1.153613
             No Downsample, BasicBlock 3         4          12345 10    25030 ViT-S      1.320759
             Downsample, BasicBlock    3         4          12345 10    25030 ViT-S      1.675239

                                                                                         Time/Img Per Sec  \
Architecture Adapter                   Src Stage Dest Stage Seed  Epoch Step  core_arch
ViT-S        No Downsample, BasicBlock 1         1          12345 10    25030 ViT-S           1588.383834
             Downsample, BasicBlock    1         1          12345 10    25030 ViT-S           1601.397229
             No Downsample, BasicBlock 1         2          12345 10    25030 ViT-S           1717.920950
             Downsample, BasicBlock    1         2          12345 10    25030 ViT-S           1742.071797
             No Downsample, BasicBlock 1         3          12345 10    25030 ViT-S           2000.900356
             Downsample, BasicBlock    1         3          12345 10    25030 ViT-S           2000.675005
             No Downsample, BasicBlock 1         4          12345 10    25030 ViT-S           2333.986830
             Downsample, BasicBlock    1         4          12345 10    25030 ViT-S           2368.882572
             No Downsample, BasicBlock 2         2          12345 10    25030 ViT-S           1861.882463
             Downsample, BasicBlock    2         2          12345 10    25030 ViT-S           1865.344130
             No Downsample, BasicBlock 2         3          12345 10    25030 ViT-S           2033.150128
             Downsample, BasicBlock    2         3          12345 10    25030 ViT-S           2078.760742
             No Downsample, BasicBlock 2         4          12345 10    25030 ViT-S           2472.611132

In [77]:
# Find missing results.
for cfgfile in tqdm(list(sorted(proj_dir.rglob("config.yml")))):
    result_files = list(cfgfile.parent.glob("result*.pkl"))
    if not result_files:
        print(f"Missing: {cfgfile.parent}")

100%|██████████| 1831/1831 [00:00<00:00, 53052.84it/s]

Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,6-adapter-finetune
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3/train-mobilenet-v3-gap-3,6-adapter-finetune
Missing: ../experiments/across-scales/mobilenet-v3-lr-2.0e-4/train-mobilenet-v3-lr-2.0e-4-gap-1,6-adapter-finetune
Missing: ../experiments/across-scales/mobilenet-v3-lr-2.0e-4/train-mobilenet-v3-lr-2.0e-4-gap-3,6-adapter-finetune
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/mobilenet-v3-resnet-50/train-mobilenet-v3-resnet-50-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,2-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,4-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50/train-resnet-50-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,1-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,1-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,1-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-mobilenet-v3/train-resnet-50-mobilenet-v3-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,1-adapter-finetune
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-finetune
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-finetune
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,6-adapter-finetune
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-3,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-3,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-3,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-swin-t/train-resnet-50-swin-t-gap-3,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,1-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,2-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-1,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,3-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,4-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-3,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,5-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-bottleneck_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-bottleneck_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-conv3x3_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_3x3conv
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_block
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_bottleneck
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_linear
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-downsample_then_linear_relu
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-linear_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s/train-resnet-50-vit-s-gap-5,6-adapter-linear_relu_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s-bert-token-ones/train-resnet-50-vit-s-gap-1,1-adapter-block_no_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s-bert-token-ones/train-resnet-50-vit-s-gap-1,1-adapter-block_with_downsample
Missing: ../experiments/across-scales/resnet-50-vit-s-bert-token-ones/train-resnet-50-vit-s-gap-1,1-adapter-bottleneck_no_downsample

In [85]:
from matplotlib import colormaps

colormaps["tab20"].colors[0]

(0.12156862745098039, 0.4666666666666667, 0.7058823529411765)